# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      build:
        working_directory: ~/idrice
        docker:
          - image: circleci/node:10-browsers-legacy
        steps:
          - checkout
           key: idrice-{{ .Branch }}-{{ checksum "package.json" }}
           - run: npm install
           - save_cache:
            key: idrice-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
              - "node_modules"
           - run:
              name: compiles the app into an output directory name dist/
              command: npm run build
           - run:
              name: Deploy the app into an output directory named docs for app
              command: npm run deploy