version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine: true
    steps:
      - run:
          name: TODO- CircleCi Must be removed from project @Idrice - We USE GitHub Action script build.yml
          command: echo "We don't need CircleCI  any more ..-- We USE GitHub Action script build.yml"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
